generator:
  # Other verbose stuff
  verbose: false
  # Show the generated grasp arrows
  show_grasp_arrows: false
  show_grasp_arrows_speed: 0.0001
  # Show hand of generated grasps
  show_prefiltered_grasps: false
  show_prefiltered_grasps_speed: 0.01

filter:
  # Collision checking in verbose
  collision_verbose: false
  collision_verbose_speed: 1.0
  # Show post-filter arrows
  show_filtered_grasps: true
  # Show pose-filter arm ik solutions
  show_filtered_arm_solutions: false
  show_filtered_arm_solutions_pregrasp_speed: 0.5
  show_filtered_arm_solutions_speed: 1.0






  