generator:
  # Show the arrows
  verbose: true
  # Show hand of generated grasps
  show_prefiltered_grasps: false
  show_prefiltered_grasps_speed: 0.1

filter:
  # Collision checking in verbose
  collision_verbose: false
  collision_verbose_speed: 1.0
  # Show post-filter arrows
  show_filtered_grasps: true
  # Show pose-filter arm ik solutions
  show_filtered_arm_solutions: false
  show_filtered_arm_solutions_pregrasp_speed: 0.5
  show_filtered_arm_solutions_speed: 1.0






  